# Project information
site_name: "Introduction to UNIX command-line"
repo_url: https://github.com/bajicv/unix_intro
site_author: Vladimir Bajić


# Theme
theme: 
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - bash

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true

# Pages  
nav:
    - Home: 01_index.md
    - Background: 02_background.md
    - Starting terminal: 03_starting.md
    - Shell syntax: 04_shell_syntax.md
    - Navigating Files and Directories: 05_navigating.md
    - Making Files and Directories: 06_making_files_and_dirs.md
    - Copying files and directories locally and remotely: 07_cp_scp.md
    - Moving, renaming and removing files and directories: 08_mv.md
    - Accessing the content of a file: 09_accessing_file_content.md
    - Pipes and Filters: 10_pipes_filters.md
    - Wildcards and Regular Expressions (regex): 11_regex.md
    - Print lines matching a pattern: 12_grep.md
    - Working with tabular files: 13_tabular_files.md
    - Loops: 14_loops.md
    - Shell Scripts: 15_scripts.md
    - Change file mode: 16_chmod.md
    - Screen manager: 17_screen.md
    - Other useful Unix commands: 18_extra.md
    - References: 19_references.md

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - javascripts/details.js